--- 
alexa_site_verification: ~
analytics: 
  google: 
    tracking_id: ~
  provider: google-universal
atom_feed: 
  path: ~
author: 
  avatar: profile.png
  bio: "Research associate in the department of mathematics at University College London"
  bitbucket: ~
  codepen: ~
  dribbble: ~
  email: "j.lagace AT ucl DOT ac DOT uk"
  employer: ~
  facebook: ~
  flickr: ~
  foursquare: ~
  github: ~
  google_plus: ~
  googlescholar: "https://scholar.google.ca/citations?user=xoJjgZsAAAAJ&hl=en"
  instagram: ~
  keybase: ~
  lastfm: ~
  linkedin: ~
  location: Location
  name: "Jean Lagacé"
  orcid: "http://orcid.org/0000-0001-7656-4433"
  pinterest: ~
  soundcloud: ~
  stackoverflow: ~
  steam: ~
  tumblr: ~
  twitter: ~
  uri: ~
  weibo: ~
  wikipedia: ~
  xing: ~
  youtube: ~
baseurl: ""
bing_site_verification: ~
breadcrumbs: false
category_archive: 
  path: /categories/
  type: liquid
collections: 
  portfolio: 
    output: true
    permalink: "/:collection/:path/"
  publications: 
    output: true
    permalink: "/:collection/:path/"
  talks: 
    output: true
    permalink: "/:collection/:path/"
  teaching: 
    output: true
    permalink: "/:collection/:path/"
comments: 
  discourse: 
    server: ~
  disqus: 
    shortname: ~
  facebook: 
    appid: ~
    colorscheme: ~
    num_posts: ~
  provider: ~
compress_html: 
  clippings: all
  ignore: 
    envs: development
defaults: 
  - 
    scope: 
      path: ""
      type: posts
    values: 
      author_profile: true
      comments: true
      layout: single
      read_time: true
      related: true
      share: true
  - 
    scope: 
      path: ""
      type: pages
    values: 
      author_profile: true
      layout: single
  - 
    scope: 
      path: ""
      type: teaching
    values: 
      author_profile: true
      comments: true
      layout: single
      share: true
  - 
    scope: 
      path: ""
      type: publications
    values: 
      author_profile: true
      comments: true
      layout: single
      share: true
  - 
    scope: 
      path: ""
      type: portfolio
    values: 
      author_profile: true
      comments: true
      layout: single
      share: true
  - 
    scope: 
      path: ""
      type: seminar
    values: 
      author_profile: true
      comments: true
      layout: single
      share: true
  - 
    scope: 
      path: ""
      type: talks
    values: 
      author_profile: true
      layout: talk
      share: true
description: "personal description"
encoding: utf-8
excerpt_separator: "\n\n"
exclude: 
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
facebook: 
  app_id: ~
  publisher: ~
  username: ~
gems: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
google_site_verification: ~
highlighter: rouge
include: 
  - .htaccess
  - _pages
  - files
incremental: false
keep_files: 
  - .git
  - .svn
kramdown: 
  auto_ids: true
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  hard_wrap: false
  input: GFM
  smart_quotes: "lsquo,rsquo,ldquo,rdquo"
  toc_levels: "1..6"
locale: en-US
lsi: false
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
name: "Jean Lagacé"
og_image: ~
permalink: "/:categories/:title/"
read_more: enabled
repository: lagacejean/lagacejean.github.io
sass: 
  sass_dir: _sass
  style: compressed
social: 
  links: ~
  name: ~
  type: ~
staticman: 
  allowedFields: 
    - name
    - email
    - url
    - message
  branch: gh-pages
  commitMessage: "New comment."
  filename: "comment-{@timestamp}"
  format: yml
  generatedFields: 
    date: 
      options: 
        format: iso8601
      type: date
  moderation: true
  path: "_data/comments/{options.slug}"
  requiredFields: 
    - name
    - email
    - message
  transforms: 
    email: md5
tag_archive: 
  path: /tags/
  type: liquid
teaser: ~
timezone: America/Los_Angeles
title: "Jean Lagacé"
title_separator: "-"
twitter: 
  username: ~
url: "https://lagacejean.github.io"
whitelist: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
words_per_minute: 160
yandex_site_verification: ~
